services:
   mglearn:
      build:
         context: .
         dockerfile: Dockerfile
      volumes:
         - ./:/app
      ports:
         - "8888:8888"
      platform: linux/amd64
      tty: true
      stdin_open: true
      command: tail -f /dev/null